### PR TITLE
Fix/#6 bug unique personal code

### LINKED ISSUE #6: Bug: Personal Code should be unique
# Personal Code should be unique

It is currently possible to add multiple attendee's with the same Personal Code. This should not be allowed, a Personal Code is a unique identifier for a person within our organisation.

- [x] Enforce Unique via Database
- [x] Enforce Unique via Service layer

### PR DESCRIPTION
**Pull request by ranudero**
# Pull Request: #[Issue number] [Issue title]

## Changes summary

[Summarize the changes you made to the project, you can let yourself be guided by the commit history]

## Checklist before requesting a review
_Remove unnecessary checks_
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (80% coverage)
- [ ] I have updated the documentation
- [x] I have run the tests locally
- [x] I have run the tests on the native image (if applicable)

## Checklist for a reviewer
_Remove unnecessary checks_
- [ ] Pull the repository and branch locally and manually test the changes.
- [ ] Does the code follow the style guidelines of the project
- [ ] All tests are passing
- [ ] Does the described functionality work as proposed for both the happy and unhappy paths
- [ ] All questions/discussions resolved
- [ ] Necessary documentation updated/added

### CODE REVIEW

File: src/main/java/com/example/eventplanner/apis/AttendeeController.java [hunk 1]
```diff
@@ -18,7 +18,7 @@ public class AttendeeController {
     private final AttendeeService attendeePostgreSqlService;
 
     @PostMapping
-    public CreatedAttendeeDTO addAttendee(@RequestBody @Valid SignupNewAttendeeCommand newAttendee) {
+    public CreatedAttendeeDTO addAttendee(@RequestBody @Valid SignupNewAttendeeCommand newAttendee) throws AttendeeWithDuplicatePersonalCodeException {
```
Comment (N1cky94) [inline src/main/java/com/example/eventplanner/apis/AttendeeController.java]: Deze `throws AttendeeWithDuplicatePersonalCodeException` is overbodig in de method header

File: src/main/java/com/example/eventplanner/services/AttendeeService.java [hunk 2]
```diff
@@ -4,9 +4,10 @@
 import com.example.eventplanner.domain.PersonalCode;
 import com.example.eventplanner.dtos.CreatedAttendeeDTO;
 import com.example.eventplanner.dtos.SignupNewAttendeeCommand;
+import com.example.eventplanner.exceptions.AttendeeWithDuplicatePersonalCodeException;
 
 
 public interface AttendeeService {
-    CreatedAttendeeDTO addAttendee(SignupNewAttendeeCommand newAttendee);
+    CreatedAttendeeDTO addAttendee(SignupNewAttendeeCommand newAttendee) throws AttendeeWithDuplicatePersonalCodeException;
```
Comment (N1cky94) [inline src/main/java/com/example/eventplanner/services/AttendeeService.java]: Deze `throws ...` hoeft hier niet te staan in de method heading.

File: src/test/java/com/example/eventplanner/services/AttendeePostgreSqlServiceTest.java [hunk 3]
```diff
@@ -44,7 +47,7 @@ void setUp() {
 
     @Test
     @DisplayName("Test if addAttendee method saves the attendee")
-    void testAddAttendee_happyFlow() {
+    void testAddAttendee_happyFlow() throws AttendeeWithDuplicatePersonalCodeException {
```
Comment (N1cky94) [inline src/test/java/com/example/eventplanner/services/AttendeePostgreSqlServiceTest.java]: Overbodige `throws ...` in de method heading.

**Review by N1cky94 — CHANGES_REQUESTED** [review]
Minor changes requested to clean up the method headers

**Review by N1cky94 — APPROVED** [review]
